version: '3.8'

services:
  api:
    build: .
    container_name: mural-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mural-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always
